/*
 * Copyright (c) 2022, salesforce.com, inc.
 * All rights reserved.
 * Licensed under the BSD 3-Clause license.
 * For full license text, see LICENSE.txt file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */
import { execCmd, TestSession } from '@salesforce/cli-plugins-testkit';
import { Lifecycle, Messages, SandboxEvents, SandboxProcessObject, SfError, StatusEvent } from '@salesforce/core';
import { expect } from 'chai';

Messages.importMessagesDirectory(__dirname);
const messages = Messages.loadMessages('@salesforce/plugin-env', 'create.sandbox');

describe('Sandbox Orgs', () => {
  let session: TestSession;

  before(async () => {
    session = await TestSession.create({
      project: { name: 'sandboxCreate' },
    });
  });

  it('will create a sandbox, verify it can be opened, and then attempt to delete it', async () => {
    let result: SandboxProcessObject;
    try {
      Lifecycle.getInstance().on(SandboxEvents.EVENT_STATUS, async (results: StatusEvent) => {
        // eslint-disable-next-line no-console
        console.log('sandbox copy progress', results.sandboxProcessObj.CopyProgress);
      });
      result = execCmd<SandboxProcessObject>(
        // TODO: revert to org:create once out of beta
        `env:create:sandbox -a mySandbox -s -p1 licenseType='Developer' -w 60 -o ${process.env.TESTKIT_HUB_USERNAME} --json`,
        { timeout: 3600000 }
      ).jsonOutput.result;
      // autogenerated sandbox names start with 'sbx'
      expect(result.CopyProgress, 'env:create:sandbox').to.equal(100);
      expect(result.SandboxName.startsWith('sbx'), 'env:create:sandbox').to.be.true;
    } catch (e) {
      const error = e as SfError;
      // there was a DNS issue, verify we handled it as best as we could
      expect(error.message, 'env:create:sandbox DNS issue').to.include(messages.getMessage('partialSuccess'));
      expect(error.message, 'env:create:sandbox DNS issue').to.include(messages.getMessage('dnsTimeout'));
      expect(error.exitCode, 'env:create:sandbox DNS issue').to.equal(68);
    }
    const sandboxUsername = `${process.env.TESTKIT_HUB_USERNAME}.${result.SandboxName}`;
    // even if a DNS issue occurred, the sandbox should still be present and available.
    const openResult = execCmd<{ username: string }>('env:open -e mySandbox --urlonly --json', {
      ensureExitCode: 0,
    }).jsonOutput.result;
    expect(openResult, 'env:open').to.be.ok;
    expect(openResult.username, 'env:open').to.equal(sandboxUsername);

    const deleteResult = execCmd<{ username: string }>('delete:org -o mySandbox --no-prompt --json', {
      ensureExitCode: 0,
    }).jsonOutput.result;
    expect(deleteResult, 'delete:org').to.be.ok;
    expect(deleteResult.username, 'delete:org').to.equal(sandboxUsername);
  });

  after(async () => {
    try {
      await session?.clean();
    } catch (e) {
      // do nothing, session?.clean() will try to remove files already removed by the org:delete and throw an error
      // it will also unwrap other stubbed methods
    }
  });
});
