# test push
name: unitTests
on:
  push:
    branches: [sm/gha]
  workflow_dispatch:

jobs:
  unit-tests:
    strategy:
      matrix:
        os: ['windows-latest', 'ubuntu-latest']
        node: [latest, lts/*]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - run: yarn install
      - run: yarn build
      - run: yarn test
