# test push
name: pr-validation

on:
  workflow_dispatch:
  push:
    branches-ignore: [main]
  pull_request:
    types: [opened, reopened, edited]
    branches: [main]

jobs:
  pr-validation:
    runs-on: 'ubuntu-latest'
    if: |
      github.event.actor.login != 'dependabot' &&
      github.event.actor.login != 'SF-CLI-BOT' &&
      !contains(github github.event.pull_request.title, '@W-') &&
      !contains(github github.event.pull_request.body, '@W-') &&
      !contains(github github.event.pull_request.title, '#') &&
      !contains(github github.event.pull_request.body, '#')
    steps:
      - name: validate PR
        run: |
          echo "PR does not reference work item or github issue"
          exit 1
