# test push
name: pr-validation

on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, reopened, edited]
    # only applies to PRs that want to merge to main
    branches: [main]

jobs:
  pr-validation:
    runs-on: 'ubuntu-latest'
    steps:
      - run: |
          echo "${{ github.event.pull_request.title }}"
          echo "${{ format(github.event.pull_request.body, '\r', '\n', ' ') }}"
          echo "${${{ github.event.pull_request.body }}//$'\r'}"
          echo "${{ github.event.pull_request.user.login }}"
      - name: bypass for bots
        if: |
          github.event.pull_request.user.login != 'dependabot' ||
          github.event.pull_request.user.login != 'SF-CLI-BOT'
        run: |
          echo "Approving PR from a bot"
      - name: body contains gus WI
        if: |
          echo !contains(github.event.pull_request.body, '@W-')
        run: |
          echo "PR does not reference work item or github issue"
          exit 1
