# test push
name: pr-validation

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited]
    # only applies to PRs that want to merge to main
    branches: [main]

jobs:
  pr-validation:
    runs-on: 'ubuntu-latest'
    steps:
      - run: |
          echo "${{ github.event.pull_request.title }}"
          echo "${{ github.event.pull_request.body }}"
          echo "${{ github.event.pull_request.user.login }}"
      - name: validate PR
        if: |
          github.event.pull_request.user.login != 'dependabot' &&
          github.event.pull_request.user.login != 'SF-CLI-BOT' &&
          !contains(github.event.pull_request.title, '@W-') &&
          !contains(github.event.pull_request.body, '@W-')
        run: |
          echo "PR does not reference work item or github issue"
          exit 1
